# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-10-10 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20201010_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sport',
            field=models.CharField(max_length=30),
        ),
    ]
